### PR TITLE
Fix missing parameters in spokes pipe creation

### LINKED ISSUE #212: Create spoke first time bst is used

### PR DESCRIPTION
**Pull request by jperata**
Fixes #212

### CODE REVIEW

File: lib/external/spokes.ts [hunk 1]
```diff
@@ -48,19 +47,25 @@ export class SpokesClient {
...
-                // Should be the same as the UUID - also the secret key
-                diagnosticsKey: this._secretKey,
-                endpoint: {
+                diagnosticsKey: null,
+                endPoint: {
                     // The unique name/ID for the skill
                     name: this._id,
                 },
+                http: {
+                    url: `https://proxy.bespoken.tools?node-id=${this._secretKey}`,
```
Comment (jkelvie) [inline lib/external/spokes.ts]: This should just be `https://proxy.bespoken.tools` instead of `https://proxy.bespoken.tools?node-id=${this._secretKey}`. That is why we are getting the an error message "Node id is not active: <UUID>,<UUID>"

Comment (jperata) [inline lib/external/spokes.ts]: Fixed

File: lib/client/bst-config.ts [hunk 2]
```diff
@@ -112,7 +112,7 @@ export class BSTConfig {
         const pipeInfo = await BSTConfig.createSpokesPipe();
 
         return {
-            "sourceID": pipeInfo.endpoint.name,
+            "sourceID": pipeInfo.endPoint.name,
```
Comment (chris-ramon) [inline lib/client/bst-config.ts]: Just curious, is this a tslint recommendation?, otherwise we might want to only camelcase not compound words 🙂 - ref: https://softwareengineering.stackexchange.com/a/230165

Comment (jperata) [inline lib/client/bst-config.ts]: not a tslint recommendation, but this is how it's named in spokes. So it's named like this for consistency.
